Header header

float64 vehicle_latitude
float64 vehicle_longitude
float64 vehicle_altitude
float64 vehicle_x
float64 vehicle_y
float64 vehicle_z
float64 vehicle_s
float64 vehicle_l
float64 vehicle_width
float64 vehicle_length
float64 head_distance

ads_TrackTarget[] fusion_results

float64 safe_stop_dis
float64 wait_dis

ads_ReferencePoint[] reference_points
ads_Spline[] reference_splines

uint8 decision

string debug_info



