Header header

#float64 vehicle_latitude
#float64 vehicle_longitude
#float64 vehicle_altitude
#float64 vehicle_x
#float64 vehicle_y
#float64 vehicle_z
#float64 vehicle_s
#float64 vehicle_l
#float64 vehicle_width
#float64 vehicle_length
#float64 head_distance

float64 vehicle_enu_x
float64 vehicle_enu_y
float64 vehicle_enu_z
float64 vehicle_pitch
float64 vehicle_roll
float64 vehicle_yaw
ads_Point front_axle_center
ads_Point rear_axle_center
ads_Point head_point
ads_Point rear_point
ads_Point hinge_point
float64 front_vehicle_length
float64 front_vehicle_width
float64 rear_vehicle_length
float64 rear_vehicle_width
float64 steering_angle

ads_TrackTarget[] fusion_results

float64 safe_stop_dis
float64 wait_dis

ads_ReferencePoint[] reference_points
ads_Spline[] reference_splines

uint8 decision

string debug_info



