#These ID will be used by ads_int2int_item.msg

uint32 item_light = 0
uint32 item_trash_lift = 1
uint32 item_trash_back = 2
uint32 item_reversing_light = 3
uint32 item_brake_light = 4
uint32 item_left_turn_light = 5
uint32 item_right_turn_light = 6
uint32 item_high_beam_light = 7
uint32 item_low_beam_light = 8
uint32 item_width_light = 9

uint32 item_brush_position = 10
uint32 item_brush_run = 11

uint32 item_suction_position = 12
uint32 item_suction_run = 13

uint32 item_spout_water_run = 14
