Header header

uint8 driving_mode
uint8 gear
uint8 clear_auto_driving
uint8 parking
uint8 light
uint8 throttle
float32 speed
uint8 battery
uint8 fan_hz
uint8 steering
uint8 brake
uint8 trash_lift_ready
uint8 trash_back_ready
uint8 reversing_light
uint8 brake_light
uint8 left_turn_light
uint8 right_turn_light
uint8 high_beam_light
uint8 low_beam_light
uint8 width_light
uint8 sweeper_enable
uint8 working_mode

