<?xml version="1.0"?> 
<robot name="rbo" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

  <!-- variable --> 
  <xacro:property name="PI" value="3.1415926"/> 
  <xacro:property name="car_width" value="1.0"/> 
  <xacro:property name="car_length" value="2.0"/> 
  <xacro:property name="car_height" value="0.3"/> 
  <xacro:property name="wheel_length" value="0.1"/> 
  <xacro:property name="wheel_radius" value="0.2"/> 
  <xacro:property name="wheel_origin_xyz" value="0.0 0.0 0.0"/> 
  <xacro:property name="wheel_origin_rpy" value="0.0 ${PI/2} 0.0"/> 
  <xacro:property name="imu_width" value="1.0"/> 
  <xacro:property name="imu_length" value="2.0"/> 
  <xacro:property name="imu_height" value="0.3"/> 

  <!-- rviz color --> 
  <material name="blue"> 
    <color rgba="0 0 1 1"/> 
  </material> 
  <material name="black"> 
    <color rgba="0 0 0 1"/> 
  </material>

  <!-- macro --> 
  <xacro:macro name="default_inertial" params="mass"> 
    <inertial> 
      <mass value="${mass}" /> 
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" /> 
    </inertial> 
  </xacro:macro> 

  <xacro:macro name="box_geometry" params="width length height"> 
    <geometry> 
      <box size="${width} ${length} ${height}"/> 
    </geometry> 
  </xacro:macro> 

  <xacro:macro name="cylinder_geometry" params="length radius"> 
    <geometry> 
      <cylinder length="${length}" radius="${radius}"/> 
    </geometry> 
  </xacro:macro> 

  <xacro:macro name="default_origin" params="xyz rpyaw"> 
    <origin xyz="${xyz}" rpy="${rpyaw}"/> 
  </xacro:macro> 

  <!-- base_link --> 
  <link name="base_link"/> 
  <joint name="base_link_car" type="fixed"> 
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/> 
    <parent link="base_link"/> 
    <child link="imu_link"/> 
  </joint>

  <link name="imu_link"> 
    <visual> 
      <xacro:box_geometry width="${imu_width}" length="${imu_length}" height="${imu_height}"/> 
      <material name="yellow"/> 
    </visual> 
    <collision> 
      <xacro:box_geometry width="${imu_width}" length="${imu_length}" height="${imu_height}"/> 
    </collision> 
    <xacro:default_inertial mass="0.05"/> 
  </link>

  <!-- wheel joint macro --> 
  <!-- right:1 left:-1 --> 
  <xacro:macro name="wheel_car_joint" params="wheel_name front_end left_right"> 
    <link name="${wheel_name}"> 
      <visual> 
        <xacro:cylinder_geometry length="${wheel_length}" radius="${wheel_radius}"/> 
        <xacro:default_origin xyz="${wheel_origin_xyz}" rpyaw="${wheel_origin_rpy}" /> 
        <material name="black"/> 
      </visual> 
      <collision> 
        <xacro:cylinder_geometry length="${wheel_length}" radius="${wheel_radius}"/> 
        <xacro:default_origin xyz="${wheel_origin_xyz}" rpyaw="${wheel_origin_rpy}" /> 
      </collision> 
      <xacro:default_inertial mass="1.0"/> 
    </link> 

    <!-- joints --> 
    <joint name="car_base_${wheel_name}" type="continuous"> 
      <origin xyz="${left_right*(wheel_length+car_width)/2.0} ${front_end*car_length*0.6/2.0} 0.0" rpy="0.0 0.0 0.0"/> 
      <parent link="imu_link"/> 
      <child link="${wheel_name}"/> 
      <axis xyz="1.0 0.0 0.0"/> 
    </joint> 

    <gazebo reference="${wheel_name}"> 
      <material>Gazebo/Black</material> 
      <mu1>0.5</mu1> 
      <mu2>0.5</mu2> 
    </gazebo> 

    <transmission name="${wheel_name}_transmission"> 
      <type>transmission_interface/SimpleTransmission</type> 
      <joint name="car_base_${wheel_name}"> 
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> 
      </joint> 
      <actuator name="${wheel_name}_motor"> 
        <mechanicalReducction>1</mechanicalReducction> 
      </actuator> 
    </transmission> 
  </xacro:macro> 

  <xacro:wheel_car_joint wheel_name="front_right_wheel" front_end="1.0" left_right="1.0"/> 
  <xacro:wheel_car_joint wheel_name="front_left_wheel" front_end="1.0" left_right="-1.0"/> 
  <xacro:wheel_car_joint wheel_name="end_right_wheel" front_end="-1.0" left_right="1.0"/> 
  <xacro:wheel_car_joint wheel_name="end_left_wheel" front_end="-1.0" left_right="-1.0"/> 

  <!-- plagin --> 
  <gazebo> 
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so"> 
      <alwaysOn>true</alwaysOn> 
      <updateRate>50.0</updateRate> 
      <leftJoint>car_base_front_left_wheel</leftJoint> 
      <rightJoint>car_base_front_right_wheel</rightJoint> 
      <wheelSeparation>1.0</wheelSeparation> 
      <wheelDiameter>0.5</wheelDiameter> 
      <torque>1.0</torque> 
      <commandTopic>cmd_vel</commandTopic> 
      <odometryTopic>odom</odometryTopic> 
      <odometryFrame>odom</odometryFrame> 
      <robotBaseFrame>base_link</robotBaseFrame> 
      <publishWheelTF>true</publishWheelTF> 
      <publishWheelJointState>true</publishWheelJointState> 
      <legecyMode>false</legecyMode> 
      <wheelAcceleration>1</wheelAcceleration> 
    </plugin> 
  </gazebo>

  <gazebo reference="imu_link"> 
    <gravity>true</gravity> 
    <sensor name="imu_sensor" type="imu"> 
      <always_on>true</always_on> 
      <update_rate>100</update_rate> 
      <visualize>true</visualize> 
      <topic>__default_topic__</topic> 
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin"> 
        <topicName>imu</topicName> 
        <bodyName>imu_link</bodyName> 
        <updateRateHZ>100.0</updateRateHZ> 
        <gaussianNoise>0.0</gaussianNoise> 
        <xyzOffset>0 0 0</xyzOffset> 
        <rpyOffset>0 0 0</rpyOffset> 
        <frameName>imu_link</frameName> 
      </plugin> 
      <pose>0 0 0 0 0 0</pose> 
    </sensor> 
  </gazebo>

</robot>
